config:
    - dev_application : "application.json"
    - production_application : "application.json"

dev_application:
    - name: "PACE (Dev)"

production_application:
    - name: "PACE (Production)"